#!/usr/bin/env bash
# Konsole theming.
#
# ONE profile, N colour schemes. konsolerc's DefaultProfile can only name a
# .profile — Konsole has no way to select a .colorscheme directly — so instead of
# a profile per theme, chase.profile stays the only profile and its
# [Appearance] ColorScheme key is rewritten on each switch. That keeps the
# per-theme state entirely in .colorscheme files.
#
# Two paths (IMPROVEMENTS.md §7.2 / §7.6):
#   1. The theme names an existing scheme in apps.konsoleScheme -> just point
#      chase.profile at it. Hand-curated schemes are never touched.
#   2. The theme names none (null) -> DERIVE a .colorscheme from the raw palette.
#
# Path 2 runs on EVERY apply, not once: editing a theme's JSON and re-selecting
# it must reproduce the terminal colours with no manual step. Generated files are
# derived state and are overwritten unconditionally.
#
# CATCH: already-running Konsole windows do not reload. A new tab or window picks
# the profile up. (qdbus is not installed on this box; live-switching every open
# session would mean walking org.kde.konsole over busctl, per session, and is not
# worth it.)
set -euo pipefail

KONSOLE_DIR="$HOME/.local/share/konsole"   # symlink into dotfiles/konsole
BASE_PROFILE="chase.profile"               # the ONLY profile: font, zsh, margin

scheme="${THEME_APP_KONSOLE_SCHEME:-}"

# hex (#rrggbb) -> "R,G,B"; Konsole rejects hex.
rgb() {
    local h="${1#\#}"
    printf '%d,%d,%d' "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

# Relative luminance, 0..1.
lum() {
    local h="${1#\#}"
    awk -v r="$((16#${h:0:2}))" -v g="$((16#${h:2:2}))" -v b="$((16#${h:4:2}))" \
        'BEGIN { printf "%.4f", (0.2126*r + 0.7152*g + 0.0722*b) / 255 }'
}

# pick <candidate> <fallback> <against>
#
# The shell's colour roles are not a terminal palette. `foregroundLight` in
# particular is a text-ON-accent role, so in a flat/monochrome theme it is set to
# the BACKGROUND colour — paperwhite has foregroundLight == background == #32302f.
# Feeding that straight into ForegroundIntense produced invisible bright-white
# text. Any derived slot that must stay legible therefore goes through here: keep
# the candidate only if it actually contrasts with <against>, else fall back.
pick() {
    local d
    d=$(awk -v a="$(lum "$1")" -v b="$(lum "$3")" \
        'BEGIN { d = a - b; print (d < 0 ? -d : d) >= 0.12 ? "ok" : "no" }')
    [ "$d" = "ok" ] && echo "$1" || echo "$2"
}

emit_colorscheme() {
    # Konsole's slots: 0=black/bg 1=red 2=green 3=yellow 4=blue 5=magenta
    # 6=cyan 7=white/fg. Normal row takes the dark* variant where the palette has
    # one, Intense takes the bright accent — that way `ls` and shell prompts get
    # the vivid colour they expect from the "bright" slot.
    local name="$1"
    cat <<SCHEME
# GENERATED by scripts/theme/konsole.sh from themes/${THEME_NAME}.json
# Do not hand-edit: any change is overwritten on the next theme switch.
# To customise this palette, edit the theme JSON, or give the theme an
# apps.konsoleProfile naming a hand-curated scheme instead.
[General]
Description=${name}
Opacity=1
Wallpaper=

[Background]
Color=$(rgb "$THEME_BACKGROUND")
[BackgroundIntense]
Color=$(rgb "$THEME_BACKGROUND_LIGHT")
[BackgroundFaint]
Color=$(rgb "$THEME_BACKGROUND_DARK")

[Foreground]
Color=$(rgb "$THEME_FOREGROUND")
[ForegroundIntense]
Color=$(rgb "$(pick "$THEME_FOREGROUND_LIGHT" "$THEME_FOREGROUND" "$THEME_BACKGROUND")")
[ForegroundFaint]
Color=$(rgb "$THEME_FOREGROUND_DARK")

[Color0]
Color=$(rgb "$THEME_BACKGROUND_DARK")
[Color0Intense]
Color=$(rgb "$THEME_GREY")
[Color0Faint]
Color=$(rgb "$THEME_BACKGROUND_DARK")

[Color1]
Color=$(rgb "$THEME_DARK_RED")
[Color1Intense]
Color=$(rgb "$THEME_RED")
[Color1Faint]
Color=$(rgb "$THEME_DARK_RED")

[Color2]
Color=$(rgb "$THEME_DARK_GREEN")
[Color2Intense]
Color=$(rgb "$THEME_GREEN")
[Color2Faint]
Color=$(rgb "$THEME_DARK_GREEN")

[Color3]
Color=$(rgb "$THEME_DARK_YELLOW")
[Color3Intense]
Color=$(rgb "$THEME_YELLOW")
[Color3Faint]
Color=$(rgb "$THEME_DARK_YELLOW")

[Color4]
Color=$(rgb "$THEME_DARK_BLUE")
[Color4Intense]
Color=$(rgb "$THEME_BLUE")
[Color4Faint]
Color=$(rgb "$THEME_DARK_BLUE")

[Color5]
Color=$(rgb "$THEME_DARK_PURPLE")
[Color5Intense]
Color=$(rgb "$THEME_PURPLE")
[Color5Faint]
Color=$(rgb "$THEME_DARK_PURPLE")

[Color6]
Color=$(rgb "$THEME_DARK_CYAN")
[Color6Intense]
Color=$(rgb "$THEME_CYAN")
[Color6Faint]
Color=$(rgb "$THEME_DARK_CYAN")

[Color7]
Color=$(rgb "$THEME_FOREGROUND")
[Color7Intense]
Color=$(rgb "$(pick "$THEME_FOREGROUND_LIGHT" "$THEME_FOREGROUND" "$THEME_BACKGROUND")")
[Color7Faint]
Color=$(rgb "$THEME_GREY_LIGHT")
SCHEME
}

if [ -n "$scheme" ]; then
    # --- Path 1: hand-curated ------------------------------------------------
    # A named scheme may live locally OR in /usr/share/konsole (the gruvbox dark
    # one does), so check both before deciding it is missing.
    if [ ! -r "${KONSOLE_DIR}/${scheme}.colorscheme" ] \
    && [ ! -r "/usr/share/konsole/${scheme}.colorscheme" ]; then
        echo "  konsole:  scheme '${scheme}' not found, skipping" >&2
        exit 0
    fi
    action="select '${scheme}'"
else
    # --- Path 2: generated ---------------------------------------------------
    scheme="${THEME_LABEL:-$THEME_NAME}"
    action="generate '${scheme}'"
    generate=1
fi

if [ -n "${DRY_RUN:-}" ]; then
    echo "  konsole:  would ${action} -> ${BASE_PROFILE} ColorScheme=${scheme}"
    exit 0
fi

[ -n "${generate:-}" ] && emit_colorscheme "$scheme" > "${KONSOLE_DIR}/${scheme}.colorscheme"

# Only the [Appearance] ColorScheme key. chase.profile's [General] block carries
# the font, Command=/bin/zsh, TerminalMargin and scrollbar position — rewriting
# the file wholesale would lose them.
kwriteconfig6 --file "${KONSOLE_DIR}/${BASE_PROFILE}" \
    --group Appearance --key ColorScheme "$scheme"
kwriteconfig6 --file konsolerc --group "Desktop Entry" --key DefaultProfile "$BASE_PROFILE"
echo "  konsole:  ${action} (new tabs only)"
