#!/usr/bin/env bash
# Qt/KDE + GTK theming.
#
# This is the only downstream target that repaints RUNNING applications:
# KColorScheme watches kdeglobals, so Dolphin, Ark, Konsole's own chrome and the
# portals recolour live. GTK largely follows for free — kde-gtk-config (6.7.4)
# regenerates ~/.config/gtk-{3,4}.0/colors.css from kdeglobals — but the icon
# theme and the dark-mode hint live in GTK's own settings.ini and are set here.
#
# Unlike konsole/zathura, nothing here is adopted into the repo: kdeglobals is
# rewritten by Plasma itself and carries far more non-theme state than theme
# state. Everything is edited in place.
set -euo pipefail

SCHEME_DIR="$HOME/.local/share/color-schemes"
GTK3_SETTINGS="$HOME/.config/gtk-3.0/settings.ini"

name="${THEME_APP_KDE_COLOR_SCHEME:-}"
icons="${THEME_APP_GTK_ICON_THEME:-}"

[ -n "$name" ] || { echo "  qtgtk:    no kdeColorScheme for this theme, skipping"; exit 0; }

rgb() {
    local h="${1#\#}"
    printf '%d,%d,%d' "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

if [ -n "${DRY_RUN:-}" ]; then
    echo "  qtgtk:    would write ${SCHEME_DIR}/${name}.colors + apply, icons=${icons:-unchanged}"
    exit 0
fi

mkdir -p "$SCHEME_DIR"

# Role mapping follows services/Colors.qml so Qt apps agree with the shell:
# primary=blue, negative=red, neutral=orange, positive=green.
BG=$(rgb "$THEME_BACKGROUND")
BG_ALT=$(rgb "$THEME_BACKGROUND_DARK")
VIEW=$(rgb "$THEME_SURFACE_LOWEST")
VIEW_ALT=$(rgb "$THEME_BACKGROUND")
BTN=$(rgb "$THEME_SURFACE_HIGH")
FG=$(rgb "$THEME_FOREGROUND")
FG_DIM=$(rgb "$THEME_GREY")
ACCENT=$(rgb "$THEME_BLUE")
SEL_FG=$(rgb "$THEME_BACKGROUND")
NEG=$(rgb "$THEME_RED")
NEU=$(rgb "$THEME_ORANGE")
POS=$(rgb "$THEME_GREEN")
LINK=$(rgb "$THEME_BLUE")
VISITED=$(rgb "$THEME_PURPLE")
DECO=$(rgb "$THEME_BACKGROUND_LIGHT")

common_fg() {
    cat <<FG
DecorationFocus=${ACCENT}
DecorationHover=${DECO}
ForegroundActive=${ACCENT}
ForegroundInactive=${FG_DIM}
ForegroundLink=${LINK}
ForegroundNegative=${NEG}
ForegroundNeutral=${NEU}
ForegroundNormal=${FG}
ForegroundPositive=${POS}
ForegroundVisited=${VISITED}
FG
}

cat > "${SCHEME_DIR}/${name}.colors" <<COLORS
# GENERATED by scripts/theme/qtgtk.sh from themes/${THEME_NAME}.json
# Do not hand-edit: overwritten on the next theme switch.
[General]
ColorScheme=${name}
Name=${THEME_LABEL:-$name}
shadeSortColumn=true
accentColorFromWallpaper=false

[KDE]
contrast=4

[Colors:Window]
BackgroundNormal=${BG}
BackgroundAlternate=${BG_ALT}
$(common_fg)

[Colors:View]
BackgroundNormal=${VIEW}
BackgroundAlternate=${VIEW_ALT}
$(common_fg)

[Colors:Button]
BackgroundNormal=${BTN}
BackgroundAlternate=${BG_ALT}
$(common_fg)

[Colors:Tooltip]
BackgroundNormal=${BG_ALT}
BackgroundAlternate=${BG}
$(common_fg)

[Colors:Complementary]
BackgroundNormal=${BG_ALT}
BackgroundAlternate=${BG}
$(common_fg)

[Colors:Selection]
BackgroundNormal=${ACCENT}
BackgroundAlternate=${ACCENT}
DecorationFocus=${ACCENT}
DecorationHover=${DECO}
ForegroundActive=${SEL_FG}
ForegroundInactive=${SEL_FG}
ForegroundLink=${SEL_FG}
ForegroundNegative=${NEG}
ForegroundNeutral=${NEU}
ForegroundNormal=${SEL_FG}
ForegroundPositive=${POS}
ForegroundVisited=${SEL_FG}

[WM]
activeBackground=${BG}
activeBlend=${BG}
activeForeground=${FG}
inactiveBackground=${BG}
inactiveBlend=${BG}
inactiveForeground=${FG_DIM}

[ColorEffects:Disabled]
Color=${BG_ALT}
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=${FG_DIM}
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0
COLORS

# plasma-apply-colorscheme writes kdeglobals and signals running Qt apps.
if command -v plasma-apply-colorscheme >/dev/null; then
    plasma-apply-colorscheme "$name" >/dev/null 2>&1 \
        || echo "  qtgtk:    plasma-apply-colorscheme failed (scheme file still written)" >&2
fi

# GTK bits kdeglobals does not cover. kwriteconfig6 handles the INI safely; the
# file is not strictly a KDE config but has the same [Section]/key=value shape.
if [ -f "$GTK3_SETTINGS" ]; then
    prefer_dark=true
    [ "${THEME_LIGHT:-false}" = "true" ] && prefer_dark=false
    kwriteconfig6 --file "$GTK3_SETTINGS" --group Settings \
        --key gtk-application-prefer-dark-theme "$prefer_dark"
    [ -n "$icons" ] && kwriteconfig6 --file "$GTK3_SETTINGS" --group Settings \
        --key gtk-icon-theme-name "$icons"
fi

# Keep Plasma's own icon setting in step with GTK's.
[ -n "$icons" ] && kwriteconfig6 --file kdeglobals --group Icons --key Theme "$icons"

echo "  qtgtk:    applied ${name}${icons:+ + icons ${icons}}"
