#!/usr/bin/env bash
# Zathura theming — generate an include file, leave zathurarc's own settings alone.
#
# zathurarc lives in this repo now (dotfiles/zathura -> ~/.config/zathura), so the
# generated file is version-controlled alongside it.
#
# CATCH: zathurarc is read at launch only. Running instances keep their colours
# until restarted; there is no reload mechanism.
set -euo pipefail

ZDIR="$HOME/.config/zathura"      # symlink into dotfiles/zathura
RC="$ZDIR/zathurarc"
THEME_RC="$ZDIR/zathurarc.theme"
INCLUDE='include zathurarc.theme'

[ -d "$ZDIR" ] || { echo "  zathura:  $ZDIR missing, skipping" >&2; exit 0; }

if [ -n "${DRY_RUN:-}" ]; then
    echo "  zathura:  would write $THEME_RC (bg ${THEME_BACKGROUND}, fg ${THEME_FOREGROUND})"
    exit 0
fi

# recolor remaps the PDF's own white -> recolor-lightcolor and black ->
# recolor-darkcolor. It stays ON for light themes too: without it zathura renders
# the page as authored (bare white), which is what "paperwhite light shows white
# pages" turned out to be. A light theme still wants the page tinted to the
# theme's off-white background, not left at #ffffff.
recolor=true

cat > "$THEME_RC" <<RC
# GENERATED by scripts/theme/zathura.sh from themes/${THEME_NAME}.json
# Do not hand-edit: overwritten on the next theme switch.
# Hand-written zathura settings belong in zathurarc, which includes this file.

set recolor                ${recolor}
set recolor-darkcolor      "${THEME_FOREGROUND}"
set recolor-lightcolor     "${THEME_BACKGROUND}"
set default-fg             "${THEME_FOREGROUND}"
set default-bg             "${THEME_BACKGROUND}"
set render-loading-fg      "${THEME_FOREGROUND}"
set render-loading-bg      "${THEME_BACKGROUND}"
set inputbar-fg            "${THEME_FOREGROUND}"
set inputbar-bg            "${THEME_BACKGROUND_DARK}"
set statusbar-fg           "${THEME_FOREGROUND}"
set statusbar-bg           "${THEME_SURFACE_HIGH}"
set highlight-color        "${THEME_YELLOW}"
set highlight-active-color "${THEME_ORANGE}"
set completion-fg          "${THEME_FOREGROUND}"
set completion-bg          "${THEME_BACKGROUND_DARK}"
set completion-highlight-fg "${THEME_BACKGROUND}"
set completion-highlight-bg "${THEME_BLUE}"
set notification-error-fg  "${THEME_FOREGROUND}"
set notification-error-bg  "${THEME_RED}"
set notification-fg        "${THEME_FOREGROUND}"
set notification-bg        "${THEME_BACKGROUND_DARK}"
RC

# Add the include exactly once. zathura applies settings in file order, so it has
# to come LAST or a hand-written colour line in zathurarc would win over it.
if [ -f "$RC" ] && ! grep -qF "$INCLUDE" "$RC"; then
    printf '\n# Generated theme colours (scripts/theme/zathura.sh). Keep last.\n%s\n' \
        "$INCLUDE" >> "$RC"
fi

echo "  zathura:  wrote zathurarc.theme (recolor ${recolor}; restart zathura to see it)"
