#! /bin/sh

external_monitor=$(xrandr --query | grep 'HDMI-1-0')
if [[ $external_monitor = HDMI-1-0\ connected* ]]; then
#    xrandr --output HDMI-1-0 --mode 1920x1080 --rotate left --left-of eDP-1
    xrandr --output HDMI-1-0 --mode 1920x1080 --rotate normal --left-of eDP-1
    xrandr --output eDP-1 --auto
	bspc monitor HDMI-1-0 -d 1 2 3 7 8 9 10
	bspc monitor eDP-1 -d 4 5 6
else
	xrandr --output eDP-1 --auto
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

eval col0=$(awk -F 'color0=' '{print $2}' ~/.cache/wal/colors.sh | sed -n 11p)

bspc config border_width        0
bspc config window_gap          20

bspc config focused_border_color $(xrdb -q | grep '*.foreground' | awk '{print $NF}')

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3' state=monocle
bspc rule -a sublime desktop='^1' state=monocle
bspc rule -a Zathura state='tiled'
bspc rule -a EVE desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pgrep -x sxhkd > /dev/null || sxhkd &
xset -b & # BEEP
picom &
#feh --bg-scale dotfiles/wallpapers/converge/converge_s3r0.jpg &
#feh --bg-scale dotfiles/wallpapers/newnew/rhombus.png &
hsetroot -solid ${col0} &
wal -R &
/usr/lib/polkit-kde-authentication-agent-1 &
~/.config/polybar/launch.sh
